name: TourGuide

on:
  push:
    branches: [ "step4" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Java & Maven
        run: |
          java -version
          mvn -v

      - name: Build with Maven
        run: mvn -f TourGuide/pom.xml clean install -B

      - name: Run tests
        run: mvn -f TourGuide/pom.xml test
